
pipelines:
  - name: jenkins_varsha
    steps:


    - name: jfrog_bash_step
      type: Bash
      execution:
        onStart:
          - echo "Step is running"
          
    - name: jfrog_jenkins_step1
      type: Jenkins
      configuration:
        inputSteps:
          - name: jfrog_bash_step
        jenkinsJobName: testvarsha
        integrations:
          - name: S_B_Jenkins

    - name: jfrog_jenkins_step2
      type: Jenkins
      configuration:
        inputSteps:
          - name: jfrog_bash_step
        jenkinsJobName: failPipeline
        integrations:
          - name: S_B_Jenkins
