pipelines:
  - name: testsimpleepipe
    
    steps:
      - name: testsimplee
        type: Bash
        execution:
          onExecute:
            - printenv
            
      - name: testsimplee2
        type: Bash
        configuration:
          inputSteps:
            - name: testsimplee
        execution:
          onExecute:
            - printenv

      - name: testsimplee3
        type: Bash
        configuration:
          inputSteps:
            - name: testsimplee
        execution:
          onExecute:
            - printenv
