
pipelines:
  - name: jenkins_varsha
    steps:

          
    - name: jfrog_jenkins_step1
      type: Jenkins
      configuration:
        jenkinsJobName: testvarsha
        integrations:
          - name: S_B_Jenkins

    - name: jfrog_jenkins_step2
      type: Jenkins
      configuration:
        inputSteps:
          - name: jfrog_jenkins_step1
        jenkinsJobName: testvarsha
        integrations:
          - name: S_B_Jenkins
